### ISSUE TITLE
Unit Test Failed With Unexpected token export

### ISSUE THREAD

**Issue by rcaner** [PaulLeCam/react-leaflet#1033]
With jest and react-testing-library leaflet components not imported on testing.   

Details:

    /Users/ios/caner/my-react-app/node_modules/@react-leaflet/core/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { useAttribution } from './attribution.js';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import React, { Component, useEffect } from "react";
    > 2 | import {
        | ^
      3 |   MapContainer,
      4 |   LayersControl,
      5 |   useMapEvents,

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/react-leaflet/lib/hooks.js:1:1)
      at Object.<anonymous> (node_modules/react-leaflet/lib/index.js:1:1)
      at Object.<anonymous> (src/Components/Map/Leafletv3/Map.tsx:2:1)
      at Object.<anonymous> (src/View/Monitoring/Satellite.tsx:4:1)
      at Object.<anonymous> (src/View/Monitoring/__tests__/Monitoring.test.tsx:4:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
