### ISSUE TITLE
Cannot mount Map in mocha tests (container not found)

### ISSUE THREAD

**Issue by dkreft** [PaulLeCam/react-leaflet#204]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.

```
$ grep -E '(react|leaflet)' package.json 
    "babel-preset-react": "^6.11.1",
    "leaflet": "^0.7.7",
    "react": "^15.3.0",
    "react-addons-test-utils": "^15.3.0",
    "react-dom": "^15.3.0",
    "react-leaflet": "^0.12.1",
    "react-redux": "^4.4.5",
```

- [x] Check that you are using a supported version of React (v0.14 or v15).
- [x] Check that you are using a supported version of Leaflet (v.0.7)
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

### Expected behavior

Inside a mocha test using `jsdom`, I would expect to be able to mount a `<Map/>` without specifying an ID of a DOM element in which to mount.

### Actual behavior

`Error: Map container not found.`

### Steps to reproduce

```js
// File: MapTest.jsx

import { expect } from 'chai'
import { mount } from 'enzyme'
import ReactTestUtils from 'react-addons-test-utils'

import React from 'react'
import { Map } from 'react-leaflet'

describe('Map', () => {
  context('when using Enzyme.mount()', () => {
    context('when no attachTo is provided', () => {
      it('mounts without problems', () => {
        mount(<Map/>)
      })
    })

    context('when an attachTo is provided', () => {
      it('mounts without problems', () => {
        mount(<Map/>, {
          attachTo: document.getElementById('test')
        })
      })
    })
  })

  context('when using ReactTestUtils.mountIntoDocument', () => {
    it('mounts without problems', () => {
      ReactTestUtils.renderIntoDocument(<Map/>)
    })
  })
})
```

```js
// File: bugReportSetup.js

// From https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md

import { jsdom } from 'jsdom'

const EXPOSED_PROPERTIES = ['window', 'navigator', 'document'];

MAIN: {
  global.document = jsdom('<div id="test"></div>')
  global.window = document.defaultView

  Object.keys(document.defaultView).forEach((property) => {
    if ( global[property] === void 0 ) {
      EXPOSED_PROPERTIES.push(property)
      global[property] = document.defaultView[property]
    }
  })
}
```

Putting it all together, here's what I get:

```
$ mocha --require test/support/bugReportSetup.js --compilers js:babel-register --require babel-polyfill test/unit/components/MapTest.jsx


  Map
    when using Enzyme.mount()
      when no attachTo is provided
        1) mounts without problems
      when an attachTo is provided
        ✓ mounts without problems (69ms)
    when using ReactTestUtils.mountIntoDocument
      2) mounts without problems


  1 passing (916ms)
  2 failing

  1) MapBug when using Enzyme.mount() when no attachTo is provided mounts without problems:
     Error: Map container not found.
      at L.Map.L.Class.extend._initContainer (node_modules/leaflet/dist/leaflet-src.js:1983:10)
      at L.Map.L.Class.extend.initialize (node_modules/leaflet/dist/leaflet-src.js:1532:8)
      at new NewClass (node_modules/leaflet/dist/leaflet-src.js:229:20)
      at Object.L.map (node_modules/leaflet/dist/leaflet-src.js:2323:9)
      at Map.componentDidMount (node_modules/react-leaflet/lib/Map.js:87:47)
      at invokeComponentDidMountWithTimer (node_modules/react/lib/ReactCompositeComponent.js:60:18)
      at CallbackQueue._assign.notifyAll (node_modules/react/lib/CallbackQueue.js:67:22)
      at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (node_modules/react/lib/ReactReconcileTransaction.js:81:26)
      at ReactReconcileTransaction.Mixin.closeAll (node_modules/react/lib/Transaction.js:204:25)
      at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:151:16)
      at batchedMountComponentIntoNode (node_modules/react/lib/ReactMount.js:126:15)
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:138:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
      at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:98:20)
      at Object.ReactMount._renderNewRootComponent (node_modules/react/lib/ReactMount.js:285:18)
      at Object.ReactMount._renderSubtreeIntoContainer (node_modules/react/lib/ReactMount.js:371:32)
      at Object.ReactMount.render (node_modules/react/lib/ReactMount.js:392:23)
      at Object.ReactTestUtils.renderIntoDocument (node_modules/react/lib/ReactTestUtils.js:85:21)
      at renderWithOptions (node_modules/enzyme/build/react-compat.js:182:26)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:94:59)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Context.<anonymous> (MapBugTest.jsx:12:9)

  2) MapBug when using ReactTestUtils.mountIntoDocument mounts without problems:
     Error: Map container not found.
      at L.Map.L.Class.extend._initContainer (node_modules/leaflet/dist/leaflet-src.js:1983:10)
      at L.Map.L.Class.extend.initialize (node_modules/leaflet/dist/leaflet-src.js:1532:8)
      at new NewClass (node_modules/leaflet/dist/leaflet-src.js:229:20)
      at Object.L.map (node_modules/leaflet/dist/leaflet-src.js:2323:9)
      at Map.componentDidMount (node_modules/react-leaflet/lib/Map.js:87:47)
      at invokeComponentDidMountWithTimer (node_modules/react/lib/ReactCompositeComponent.js:60:18)
      at CallbackQueue._assign.notifyAll (node_modules/react/lib/CallbackQueue.js:67:22)
      at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (node_modules/react/lib/ReactReconcileTransaction.js:81:26)
      at ReactReconcileTransaction.Mixin.closeAll (node_modules/react/lib/Transaction.js:204:25)
      at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:151:16)
      at batchedMountComponentIntoNode (node_modules/react/lib/ReactMount.js:126:15)
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:138:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
      at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:98:20)
      at Object.ReactMount._renderNewRootComponent (node_modules/react/lib/ReactMount.js:285:18)
      at Object.ReactMount._renderSubtreeIntoContainer (node_modules/react/lib/ReactMount.js:371:32)
      at Object.ReactMount.render (node_modules/react/lib/ReactMount.js:392:23)
      at Object.ReactTestUtils.renderIntoDocument (node_modules/react/lib/ReactTestUtils.js:85:21)
      at Context.<anonymous> (MapBugTest.jsx:27:22)
```

**Comment by PaulLeCam** [comment]
Hi,
Sorry I don't use Mocha so I don't know about its setup, if it's indeed an issue with the library please provide a jsfiddle or similar with a running example, not a specific environment like Mocha.

**Comment by dkreft** [comment]
I think the stack trace demonstrates that it is indeed a problem with the library, specifically the  library's interaction with Node + jsdom. JSFiddles run in a browser, so it's going to be impossible to reproduce the same bug.

Does this mean you're unwilling to look into this?

**Comment by PaulLeCam** [comment]
This is a client-side library so yes, sorry but I will not investigate issues specific to Node and jsdom.
If you can find a solution to your issue I would gladly review a PR but unless it is something that can be reproduced in a client-side environment, I won't focus on it myself.

**Comment by hloughrey** [comment]
@dkreft - I'm getting a similar error `'Error: Map container not found.'` when testing a Map component using Chai, Mocha and Karma - did you ever get the bottom of your issue?

**Comment by dkreft** [comment]
Nope. I just relegated myself to putting a div with an id in it and passing
that in as the container.

Sad but true.

-dan

**Comment by evansiroky** [comment]
@dkreft Thanks for the example of how to use enzyme to test react-leaflet!  I've been looking all around the interwebs and this seems to be the best example out there.

**Comment by simeonackermann** [comment]
@dkreft i know its a bit old issue, but do you have any solution for this problem? Its seems still not solved...

**Comment by evansiroky** [comment]
See my research into this issue here:  https://github.com/PaulLeCam/react-leaflet/issues/246#issuecomment-258304411

**Comment by simeonackermann** [comment]
Thanks, I ignored the attach mode.
