### ISSUE TITLE
Webpack: Generating HTML failed Error: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Ognian** [PaulLeCam/react-leaflet#303]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.0.0+).
- [x] Using the supported version of Leaflet (v1.0.0) and its corresponding CSS file is loaded.
- [x] Using the latest version of React-Leaflet.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

I'm using react-leaflet with gatsby, a static site generation framework. As long as I'm in development mode everything is ok, but as soon as I try to generate the static bundle webpack reports the following error:
```
Generating HTML failed Error: ReferenceError: window is not defined
    at Object.defineProperty.value (render-page.js:78978:4)
    at __webpack_require__ (render-page.js:30:30)
    at Object.L.version (render-page.js:65715:17)
    at __webpack_require__ (render-page.js:30:30)
    at Object.defineProperty.value (render-page.js:65665:17)
    at __webpack_require__ (render-page.js:30:30)
    at Object.defineProperty.value (render-page.js:65519:15)
    at __webpack_require__ (render-page.js:30:30)
    at Object.exports.__esModule (render-page.js:51672:22)
    at __webpack_require__ (render-page.js:30:30)
```
looks like this happens when you import leaflet
https://github.com/PaulLeCam/react-leaflet/blob/master/src/Map.js#L3
according to the [react docs](https://facebook.github.io/react/docs/react-component.html)
using window is only allowed in componentDidMount() : "Initialization that requires DOM nodes should go here. "
Others seem to have the same problem:
https://github.com/webpack/react-starter/issues/37
https://github.com/gatsbyjs/gatsby/issues/309
and solved it by using `require` instead of `import` and doing this conditionally...

What do you think?
Thanks
Ognian

**Comment by Ognian** [comment]
Sorry, understood this https://github.com/PaulLeCam/react-leaflet/issues/45
to late, therefore I'm closing this issue. I understand that this will not change soon...
